@startuml
title Bronze challenge\nsequence diagram
participant Buggy as b #4f4
participant Station as s #44f
note over b, s #fff: Buggy in parking lot, stopped

    s->b: Clockwise
    s->b: Go
...
group Under a gantry
    s<-b: Gantry 1
    s->b: Stop

    note over s #fff: Wait 1 sec
    s->b: Go
end
...
    s<->b: Under gantry 2...
    s->b: Straight
...
    s<->b: Under gantry 3...
...
    s<->b: Under gantry 1...
...
    s<->b: Under gantry 2...
    s->b: Park
    s<-b: Parked

newpage Obstacle

...
group Obstacle encountered
    b->s: Obstacle appeared
    ...
    b->s: Obstacle gone
end
...
@enduml